/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @typescript-eslint/no-explicit-any */
// app/consultations/components/AddConsultationModal.tsx
'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { ConsultationFormData } from '../types/consultation'
import { 
  X, 
  User, 
  Home, 
  Stethoscope, 
  Pill, 
  MapPin,
  CheckCircle,
  Loader2,
  AlertCircle
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'

interface AddConsultationModalProps {
  isOpen: boolean
  onClose: () => void
  onSuccess: () => void
  userId: string | null
  userRole: 'admin' | 'doctor' | null
}

const defaultFormData: ConsultationFormData = {
  patientName: '',
  patientAddress: '',
  age: '',
  sexe: undefined,
  diagnostics: '',
  dominantSigns: '',
  treatment: '',
  origin: '',
  isPregnant: false
}

export default function AddConsultationModal({
  isOpen,
  onClose,
  onSuccess,
  userId,
  userRole
}: AddConsultationModalProps) {
  const [formData, setFormData] = useState<ConsultationFormData>(defaultFormData)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  if (!isOpen) return null

  const validateForm = (): boolean => {
    if (!formData.patientName.trim()) {
      setError('Le nom du patient est requis')
      return false
    }
    
    if (formData.age) {
      const ageNum = parseInt(formData.age)
      if (isNaN(ageNum) || ageNum < 0 || ageNum > 120) {
        setError('Âge invalide. Doit être entre 0 et 120 ans')
        return false
      }
    }
    
    setError(null)
    return true
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    if (!userId) {
      setError('Utilisateur non authentifié')
      return
    }
    
    setIsSubmitting(true)
    setError(null)
    
    try {
      const supabase = createClient()
      
      // Prepare consultation data - EXACTLY matching your schema
      const consultationData = {
        patientName: formData.patientName.trim(),
        patientAddress: formData.patientAddress?.trim() || null,
        age: formData.age || null,
        sexe: formData.sexe || null,
        diagnostics: formData.diagnostics?.trim() || null,
        daminantSigns: formData.dominantSigns?.trim() || null, // FIXED: "daminantSigns" not "daminentSigns"
        treatment: formData.treatment?.trim() || null,
        origin: formData.origin?.trim() || null,
        isPregnant: formData.isPregnant || false,
        createdBy: userId
        // createdAt and consultationId are auto-generated by Supabase
      }
      
      console.log('Inserting consultation data:', consultationData)
      
      // Insert consultation
      const { data, error: insertError } = await supabase
        .from('consultations')
        .insert([consultationData])
        .select()
      
      if (insertError) {
        console.error('Supabase insert error details:', insertError)
        throw new Error(`Erreur: ${insertError.message}. Code: ${insertError.code}`)
      }
      
      console.log('Consultation added successfully! Response:', data)
      
      // Reset form
      setFormData(defaultFormData)
      
      // Show success and close modal
      alert('✅ Consultation ajoutée avec succès!')
      onSuccess()
      
    } catch (err: any) {
      console.error('Full error adding consultation:', err)
      setError(err.message || 'Erreur lors de l\'ajout de la consultation')
    } finally {
      setIsSubmitting(false)
    }
  }

  const handleChange = (field: keyof ConsultationFormData, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    if (error) setError(null)
  }

  const handleClose = () => {
    if (!isSubmitting) {
      setFormData(defaultFormData)
      setError(null)
      onClose()
    }
  }

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex min-h-screen items-center justify-center p-4">
        <div 
          className="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity"
          onClick={handleClose}
        />

        <div className="relative bg-white rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
          {/* Header */}
          <div className="sticky top-0 z-10 bg-gradient-to-r from-blue-50 to-indigo-50 border-b border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-white rounded-lg shadow-sm">
                  <Stethoscope className="h-6 w-6 text-blue-600" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-gray-900">
                    Nouvelle Consultation
                  </h2>
                  <p className="text-gray-600">
                    Remplissez les informations du patient
                  </p>
                </div>
              </div>

              <button
                onClick={handleClose}
                disabled={isSubmitting}
                className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="p-6">
            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-xl">
                <div className="flex items-start gap-3">
                  <AlertCircle className="h-5 w-5 text-red-600 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-red-700 font-medium">Erreur d'insertion</p>
                    <p className="text-red-600 text-sm">{error}</p>
                  </div>
                </div>
              </div>
            )}

            <div className="space-y-6">
              {/* Patient Information */}
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <Label className="text-gray-700 font-medium">
                      Nom complet *
                    </Label>
                    <div className="relative">
                      <User className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                      <Input
                        value={formData.patientName}
                        onChange={(e) => handleChange('patientName', e.target.value)}
                        className="pl-10"
                        placeholder="Nom et prénom du patient"
                        required
                        disabled={isSubmitting}
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label className="text-gray-700 font-medium">
                      Âge
                    </Label>
                    <Input
                      type="number"
                      min="0"
                      max="120"
                      value={formData.age}
                      onChange={(e) => handleChange('age', e.target.value)}
                      placeholder="Âge du patient"
                      disabled={isSubmitting}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <Label className="text-gray-700 font-medium">Sexe</Label>
                    <div className="flex gap-4">
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="sexe"
                          value="male"
                          checked={formData.sexe === 'male'}
                          onChange={(e) => handleChange('sexe', e.target.value)}
                          className="text-blue-600"
                          disabled={isSubmitting}
                        />
                        <span className="text-gray-700">Homme</span>
                      </label>
                      <label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="radio"
                          name="sexe"
                          value="female"
                          checked={formData.sexe === 'female'}
                          onChange={(e) => handleChange('sexe', e.target.value)}
                          className="text-pink-600"
                          disabled={isSubmitting}
                        />
                        <span className="text-gray-700">Femme</span>
                      </label>
                    </div>
                  </div>

                  {formData.sexe === 'female' && (
                    <div className="space-y-2">
                      <Label className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={formData.isPregnant}
                          onChange={(e) => handleChange('isPregnant', e.target.checked)}
                          className="rounded h-4 w-4 text-purple-600"
                          disabled={isSubmitting}
                        />
                        <span className="text-gray-700 font-medium">Patient enceinte</span>
                      </Label>
                    </div>
                  )}
                </div>
              </div>

              {/* Address Information */}
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <Label className="text-gray-700 font-medium">
                      Origine
                    </Label>
                    <Input
                      value={formData.origin}
                      onChange={(e) => handleChange('origin', e.target.value)}
                      placeholder="Ville ou région d'origine"
                      disabled={isSubmitting}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label className="text-gray-700 font-medium">
                      Adresse
                    </Label>
                    <div className="relative">
                      <MapPin className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                      <Textarea
                        value={formData.patientAddress}
                        onChange={(e) => handleChange('patientAddress', e.target.value)}
                        className="pl-10 min-h-[80px]"
                        placeholder="Adresse complète"
                        disabled={isSubmitting}
                      />
                    </div>
                  </div>
                </div>
              </div>

              {/* Medical Information */}
              <div className="space-y-6">
                <div className="space-y-2">
                  <Label className="text-gray-700 font-medium">
                    Diagnostic principal
                  </Label>
                  <div className="relative">
                    <Stethoscope className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                    <Textarea
                      value={formData.diagnostics}
                      onChange={(e) => handleChange('diagnostics', e.target.value)}
                      className="pl-10 min-h-[100px]"
                      placeholder="Décrivez le diagnostic..."
                      disabled={isSubmitting}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label className="text-gray-700 font-medium">
                    Signes dominants
                  </Label>
                  <Textarea
                    value={formData.dominantSigns}
                    onChange={(e) => handleChange('dominantSigns', e.target.value)}
                    className="min-h-[80px]"
                    placeholder="Symptômes observés..."
                    disabled={isSubmitting}
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-gray-700 font-medium">
                    Traitement prescrit
                  </Label>
                  <div className="relative">
                    <Pill className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                    <Textarea
                      value={formData.treatment}
                      onChange={(e) => handleChange('treatment', e.target.value)}
                      className="pl-10 min-h-[100px]"
                      placeholder="Médicaments, posologie..."
                      disabled={isSubmitting}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="sticky bottom-0 bg-white border-t border-gray-200 p-6 mt-8">
              <div className="flex justify-end gap-3">
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleClose}
                  disabled={isSubmitting}
                  className="border-gray-300 hover:border-gray-400 px-6"
                >
                  Annuler
                </Button>
                <Button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 shadow-lg hover:shadow-xl px-8"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Enregistrement...
                    </>
                  ) : (
                    <>
                      <CheckCircle className="h-4 w-4 mr-2" />
                      Enregistrer
                    </>
                  )}
                </Button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}